# Generated by Django 6.0.5 on 2026-07-14 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emails',
            new_name='email',
        ),
    ]
