# Generated by Django 6.0.5 on 2026-08-18 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_taskdetails_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='tasks.task'),
        ),
    ]
