# Generated by Django 6.0.5 on 2026-09-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
