# Generated by Django 6.0.5 on 2026-09-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskdetails_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_asset/default.jpg', null=True, upload_to='tasks_asset'),
        ),
    ]
